### ISSUE TITLE
[ISSUE] Error creating Databricks workspace using terraform in AWS Databricks

### ISSUE THREAD

**Issue by JimmyNguyen24** [databricks/databricks-sdk-go#1040]
**Description**
Error creating Databricks workspace using terraform in AWS Databricks.

_Error: cannot create mws workspaces: unexpected error handling request: invalid character 'M' looking for beginning of value. This is likely a bug in the Databricks SDK for Go or the underlying REST API._ 

**Reproduction**
  + resource "databricks_mws_workspaces" "workspace" {
      + account_id               = (sensitive value)
      + aws_region               = "us-east-1"
      + cloud                    = (known after apply)
      + creation_time            = (known after apply)
      + credentials_id           = xxxxxx
      + id                       = (known after apply)
      + is_no_public_ip_enabled  = true
      + network_id               = "b6afe7bb-69f1-42be-b2a6-1ecc5d2b3d97/cc4ef48a-db4b-48ce-802b-372d81adae6e"
      + pricing_tier             = (known after apply)
      + storage_configuration_id = "b6afe7bb-69f1-42be-b2a6-1ecc5d2b3d97/d7273a90-c17d-416d-b66f-e83b0e6e7e18"
      + workspace_id             = (known after apply)
      + workspace_name           = "databricks-staging"
      + workspace_status         = (known after apply)
      + workspace_status_message = (known after apply)
      + workspace_url            = (known after apply)
    }

**Expected behavior**
The Databricks workspace should be created

**Is it a regression?**
To my knowledge, this has never worked before, and other users are also reporting the same issue.

**Debug Logs**
POST /api/2.0/accounts/xxxxxxxxx/workspaces
> * Host: 
> * Accept: application/json
> * Authorization: REDACTED
> * Content-Type: application/json
> * User-Agent: databricks-tf-provider/1.38.0 databricks-sdk-go/0.33.0 go/1.21.7 os/linux terraform/1.4.2 resource/mws_workspaces auth/oauth-m2m cicd/github
> {
>   "account_id": "xxxxxxx",
>   "aws_region": "us-east-1",
>   "credentials_id": "xxxxxx",
>   "is_no_public_ip_enabled": true,
>   "network_id": "b6afe7bb-69f1-42be-b2a6-1ecc5d2b3d97/cc4ef48a-db4b-48ce-802b-372d81adae6e",
>   "storage_configuration_id": "b6afe7bb-69f1-42be-b2a6-1ecc5d2b3d97/d7273a90-c17d-416d-b66f-e83b0e6e7e18",
>   "workspace_name": "databricks-staging"
> }
< HTTP/2.0 400 Bad Request
< * Content-Type: text/plain; charset=utf-8
< * Date: Tue, 03 Sep 2024 22:50:44 GMT
< * Server: databricks
< * Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< * Vary: Accept-Encoding
< * X-Content-Type-Options: nosniff
< * X-Request-Id: 2e402f44-4cd9-4184-a5db-3f6bb70b6d92
< MALFORMED_REQUEST: Cannot parse request body: {"account_id":"xxxxxxxx","workspace_name":"databricks-staging","aws_region":"us-east-1","credentials_id":"xxxxxxx","storage_configuration_id":"b6afe7bb-69f1-42be-b2a6-1ecc5d2b3d97/d7273a90-c17d-416d-b66f-e83b0e6e7e18","network_id":"b6afe7bb-69f1-42be-b2a6-1ecc5d2b3d97/cc4ef48a-db4b-48ce-802b-372d81adae6e","is_no_public_ip_enabled":true}

**Other Information**
 - OS: macOS
 - Version: 14.6.1

**Comment by samuelberntzen** [comment]
I experienced the same issue. It was caused by retrieving wrong _mws credentials id_ from `the databricks_mws_credentials` resource. 

The `databricks_mws_credentials` has 2 ID attributes: `id` and `credentials_id` which are easily mixed up. Check if you are using the correct one in the creation of the workspace.

Example from the documentation:
```
resource "databricks_mws_workspaces" "this" {
  provider       = databricks.mws
  account_id     = var.databricks_account_id
  aws_region     = var.aws_region
  workspace_name = local.prefix

  credentials_id           = databricks_mws_credentials.this.credentials_id
  storage_configuration_id = databricks_mws_storage_configurations.this.storage_configuration_id
  network_id               = databricks_mws_networks.this.network_id

  token {
    comment = "Terraform"
  }
}
```

or if you did like me and created the `databricks_mws_credentials` in a submodule, check if you are outputing it correctly:
```
output "databricks_mws_credentials_id" {
  value = databricks_mws_credentials.this.credentials_id
}
```

**Comment by JimmyNguyen24** [comment]
Thank you @samuelberntzen. That resolved my issue!
