### ISSUE TITLE
Jobs List API doesn't handle has_more parameter

### ISSUE THREAD

**Issue by alexott** [databricks/databricks-sdk-go#173]
jobs.[List](https://github.com/databricks/databricks-sdk-go/blob/6cb519cfade757d66a05088e960eac47ed272149/service/jobs/impl.go#L75) function doesn't use `has_more` parameter, so there will be incomplete results.

**Comment by mgyucht** [comment]
Jobs list now uses token-based pagination to fetch the complete list of results, so I'll close this out.
