### ISSUE TITLE
High Level Feedback

### ISSUE THREAD

**Issue by carl-db** [databricks/databricks-sdk-go#209]
https://github.com/databricks/databricks-sdk-go/blob/main/useragent/user_agent.go
* Is there a reason for these fields to be set globally vs inside client creation? I'm not a huge fan of the usage of `init` + global state with these

https://github.com/databricks/databricks-sdk-go/blob/main/alias.go#L13
* The `Must[T]` function doesn't seem like the kind of thing we'd want to expose in a stable SDK? I'm also wondering if this is the only thing that locks out compatability to go 1.18, ideally we could would with at least 1.16 (for customers that might not be on latest -- or us!)
* While it's convinient for terse examples, I'm generally a fan of examples using a normal error flow (we don't want people copy/pasting `Must` into their code, but it will inevitably happen)

https://github.com/databricks/databricks-sdk-go/blob/main/examples/custom-auth/main.go
* In these examples, where is `println` declared? Any reason this can't be the normal `fmt.Println`?
* Similar to the above, could we hoist the code in `func main()` into a function that returns errors for better copy+pastability?

### DatabricksClient struct vs interface

Was there discussion of struct vs interface for `client.DatabricksClient`? It seems to be the main entrypoint into I/O for the SDK, this feels to me like a helpful place to put an interface boundary. (for mocking, clear deliniation of what I/O needs, and flexibility of API down the line)

The thing that really sticks out to me is customers potentially being able to provide their own `http.Client` for the connections -- we set a lot of knobs that they may want to control on their side like dial context, timeouts, and TLS params (https://github.com/databricks/databricks-sdk-go/blob/main/client/client.go#L39).

**Comment by nfx** [comment]
@carl-db  thank you for the feedback! I'll close this issue and rather open a discussion :)
