### ISSUE TITLE
Explicit propagation for `json,"..,optional"` fields

### ISSUE THREAD

**Issue by nfx** [databricks/databricks-sdk-go#268]
fix cases around optional propagation:

```go
func isOptional(typeField reflect.StructField) bool {
	if strings.Contains(typeField.Tag.Get("json"), "omitempty") {
		return true
	}
	tfTags := strings.Split(typeField.Tag.Get("tf"), ",")
	for _, tag := range tfTags {
		if tag == "optional" {
			return true
		}
	}
	return false
}
...
                omitEmpty := isOptional(typeField)
		if omitEmpty && !fieldSchema.Optional {
			return fmt.Errorf("inconsistency: %s has omitempty, but is not optional", fieldName)
		}
```

**Comment by nfx** [comment]
Google API SDK does it through custom marshallers:

https://github.com/googleapis/google-api-go-client/blob/4dca4e00ad5b16c8a06dec1c4ae9d3b5f917406a/google-api-go-generator/gen.go#L1433-L1474

**Comment by benbauer89** [comment]
Hey, I created an issue with basically the same problem: https://github.com/databricks/terraform-provider-databricks/issues/1776
any chance this gets prioritized in one of the next releases?

**Comment by pietern** [comment]
@hectorcast-db Is working on support for this in #615 and more.

**Comment by mgyucht** [comment]
I think the Go SDK changes are complete, so we can probably close this issue? The remaining issues stem from the TF provider.

**Comment by hectorcast-db** [comment]
Correct. SDK changes are complete. Closing this issue.
