### ISSUE TITLE
Can't disable Serverless or Photon in SQL Warehouse

### ISSUE THREAD

**Issue by alexott** [databricks/databricks-sdk-go#270]
both `EnableServerlessCompute` and `EnablePhoton` are marked as `omitempty` - this means that if they set to `false`, value won't be sent to the API. 

Related terraform issue: https://github.com/databricks/terraform-provider-databricks/issues/1436

**Comment by mgyucht** [comment]
This should be possible now with ForceSendFields. We'll address the TF issue separately (I'm working on migrating that resource to the Go SDK).
