### ISSUE TITLE
APIError not using pointer receiver

### ISSUE THREAD

**Issue by amwill04** [databricks/databricks-sdk-go#285]
`APIError` implementation of `Error()` does no use pointer receiver that while does not break `errors.As` it changes how you expect to use it.

```go
_, err := db.w.Catalogs.GetByName(ctx, name)
if err != nil {
	var apiErr *apierr.APIError
	if errors.As(err, &apiErr)
            // This block is never called
	}
	return false, fmt.Errorf("catalogExists: %w", err)
}
```

I know that `IsMissing` is available to do this check but would seem better to have `APIError` work as expected.

Happy to open a PR if this is something that would be accepted

**Comment by nfx** [comment]
Hi @amwill04 , did you mean `var apiErr apierr.APIError`?

**Comment by amwill04** [comment]
Hey @nfx  - if `var apiErr apierr.APIError` is used then then issue goes away. But, my point originally was regarding that this goes against use with `errors.As` [here](https://go.dev/blog/go1.13-errors#TOC_3.2) and [here](https://pkg.go.dev/errors#example-As). You only know to use `var apiErr apierr.APIError` if you go into the `sdk` source code to see that the implementation of `APIError` uses a non-pointer receiver for the error interface.

**Comment by nfx** [comment]
Hi @amwill04 , you can go ahead with the PR :)
