### ISSUE TITLE
Cannot update share owner

### ISSUE THREAD

**Issue by marekbrysa** [databricks/databricks-sdk-go#502]
```go
w.Shares.Update(context.Background(), sharing.UpdateShare{
	Name:  shareName,
	Owner: newOwner,
})
```
Calls https://github.com/databricks/databricks-sdk-go/blob/b5bbc1c8dabba87890fadf0d3bee29d8a3452294/service/sharing/impl.go#L170
which includes the `Name` property in the request. That results in the request being rejected with `User is not an owner of Share ...`. I believe the request body should not include the `Name` property, but only the `Owner` property, then the owner could be changed (that's what a request made in the UI looks like).

When I manually add line reset `Name` before making a request, it works: https://github.com/marekbrysa/databricks-sdk-go/commit/4552f27a63abe23d12f2fd1cd702569d81d8f6ef

But not sure how to fix it as it is generated code.

**Comment by marekbrysa** [comment]
Removing the `Name` completely from the request body as I did would probably break renaming the share if you are already the owner. Ideally, we’d like the name in the url and the name in the body to be independent.

**Comment by nfx** [comment]
please raise a ticket with UC team

**Comment by wchau** [comment]
The name in the URL and the name in the body is already independent in the REST API. I am not sure what the Delta Sharing / UC team needs to do here as it seems the generated code has issues or the usage is incorrect?

**Comment by nfx** [comment]
@wchau your team is responsible for the OpenAPI spec to be correct :)

**Comment by adamcain-db** [comment]
The UC fix (adding `new_name` to all UC Update RPCs and excluding `name` from the problematic Update messages in the OpenAPI specs) is merged. The fix should be in the 12/8 UC release, to be deployed to prod Dec 14-18.

**Comment by tanmay-db** [comment]
Marking this as resolved as the release https://github.com/databricks/databricks-sdk-go/commit/01b66f269fb9e612ef3a058f3ff70483fbe79dc2 has been done.
