### ISSUE TITLE
tables.Get().Columns: Cannot distinguish partition_index

### ISSUE THREAD

**Issue by marekbrysa** [databricks/databricks-sdk-go#516]
The JSON of columns returned by API looks like this:
```
2023/06/15 07:58:26 [DEBUG] GET /api/2.1/unity-catalog/tables/foo.bar.baz
< HTTP/2.0 200 OK
< {
<   "browse_only": false,
<   "catalog_name": "foo",
<   "columns": [
<     {
<       "name": "account_id",
<       "nullable": true,
<       "partition_index": 0,
<       "position": 0,
<       "type_json": "{\"name\":\"account_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}",
<       "type_name": "STRING",
<       "type_precision": 0,
<       "type_scale": 0,
<       "type_text": "string"
<     },
<     {
<       "name": "workspace_id",
<       "nullable": true,
<       "position": 1,
<       "type_json": "{\"name\":\"workspace_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}",
<       "type_name": "STRING",
<       "type_precision": 0,
<       "type_scale": 0,
<       "type_text": "string"
<     },
<     {
<       "name": "column3",
<       "nullable": true,
<       "position": 2,
<       "type_json": "{\"name\":\"column3\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}",
<       "type_name": "STRING",
<       "type_precision": 0,
<       "type_scale": 0,
<       "type_text": "string"
<     },
```

Notably the first column has `"partition_index": 0,`, but the rest are missing it because they are not partitions.. However when that is deserialized into ColumnInfo, all columns have `PartitionIndex==0` because that is the default value when the property in JSON is missing (https://github.com/databricks/databricks-sdk-go/blob/d5e57f7cf6e9e65b2e54ccbb391fc0cfed849f06/service/catalog/model.go#L170)

This means it's impossible to determine which column is actually the 0th partition (or whether the table has a partition at all).

**Comment by mgyucht** [comment]
@marekbrysa since v0.23.0, the Go SDK includes a "ForceSendFields" in all generated structures. This field is a list of field names that are included in responses with values equal to the zero value for that type. So now, you can check for the `ColumnInfo` where `ForceSendFields` contains `"PartitionIndex"`: that will be the one with partition index of 0.
