### ISSUE TITLE
`X-Databricks-Account-Console-API-Version` Header should be added to request

### ISSUE THREAD

**Issue by rmennes** [databricks/databricks-sdk-go#526]
Currently it is not possible to load the metastores. The `X-Databricks-Account-Console-API-Version` http header is required to get the correct json result.

**Comment by nfx** [comment]
@rmennes we're working on the relevant platform change to fix this

**Comment by pietern** [comment]
This was fixed early July on the platform side.

Also see: https://github.com/databricks/cli/issues/530
