### ISSUE TITLE
[ISSUE] Incorrect definition for `GetIpAccessListResponse`

### ISSUE THREAD

**Issue by nkvuong** [databricks/databricks-sdk-go#581]
**Description**
The struct `GetIpAccessListResponse` [auto-gen](https://github.com/databricks/databricks-sdk-go/blob/main/service/settings/model.go#L140) from OpenAPI spec is wrong (should be the same as `FetchIpAccessListResponse`)

```go
type FetchIpAccessListResponse struct {
	IpAccessList *IpAccessListInfo `json:"ip_access_list,omitempty"`
}
```

This is weird as the OpenAPI spec for both `GetIpAccessListResponse` and `FetchIpAccessListResponse` are the same

**Comment by mgyucht** [comment]
They are different in OpenAPI: FetchIpAccessList returns an object with field `ip_access_list` with one IP Access List, whereas GetIpAccessLIstResponse returns an object with field `ip_access_lists` that is an array with 0 or more IP Access Lists.

**Comment by nkvuong** [comment]
Turns out this struct is defined in 2 different places with conflicting definitions - should our validation throws an error for this?
- https://github.com/databricks/universe/blob/master/acl/accounts-ip-access-list/api/openapi/accounts-ip-access-list.openapi.jsonnet#L446
- https://github.com/databricks/universe/blob/master/acl/ip-access-list/api/openapi/ip-access-list-2.0.openapi.jsonnet#L424

**Comment by mgyucht** [comment]
+1. I will create an ES ticket for the responsible team to fix.
