### ISSUE TITLE
[ISSUE] `accountStorageCredentialsImpl` generates incorrect paths

### ISSUE THREAD

**Issue by nkvuong** [databricks/databricks-sdk-go#629]
**Description**
As reported in this [TF issue](https://github.com/databricks/terraform-provider-databricks/issues/2697)
, the paths generated for `Update` function is incorrect. Comparing `accountStorageCredentialsImpl` to the [doc](https://docs.databricks.com/api/azure/account/accountstoragecredentials), the `Get` & `Delete` functions are also incorrect

All of these paths are missing the credential name
https://github.com/databricks/databricks-sdk-go/blob/a77197b1261617695f349473154f744e606a014b/service/catalog/impl.go#L129
https://github.com/databricks/databricks-sdk-go/blob/a77197b1261617695f349473154f744e606a014b/service/catalog/impl.go#L138
https://github.com/databricks/databricks-sdk-go/blob/a77197b1261617695f349473154f744e606a014b/service/catalog/impl.go#L156

**Comment by mgyucht** [comment]
This has been resolved in the latest Go SDK release.
