### ISSUE TITLE
Lack of clarity which DB connector is used under the hood

### ISSUE THREAD

**Issue by gilsegment** [databricks/databricks-sdk-go#688]
**Description**
This is a request to add a bit more info in the README regarding the connector that is used under the hood. What is used to connect to Databricks warehouse JDBC/ODBC/Something else?

Thanks !

**Reproduction**
N/A

**Expected behavior**
N/A

**Is it a regression?**
N/A

**Debug Logs**
N/A

**Other Information**
N/A

**Additional context**
N/A

**Comment by mgyucht** [comment]
No SQL driver is used in the Go SDK. If you're talking about the ExecuteStatement API, that is a REST API that executes the specified SQL query on the chosen SQL warehouse. What method are you talking about?

**Comment by mgyucht** [comment]
Any questions here? Otherwise I will close this issue out as stale.

**Comment by gilsegment** [comment]
Apologies. My question should have directed to here:
https://github.com/databricks/databricks-sql-go/issues/181
You can close the issue
