### ISSUE TITLE
issue :Error: cannot read data metastore: unexpected error handling request: unexpected end of JSON input. This is likely a bug in the Databricks SDK for Go or the underlying REST API

### ISSUE THREAD

**Issue by dmchakram** [databricks/databricks-sdk-go#766]
**Description**
Trying to read the metastore from exisiting metastore by using terraform in ADO pipeline . Its throwing below error 

**Reproduction**
Error: cannot read data metastore: unexpected error handling request: unexpected end of JSON input. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:
```
GET /api/2.0/accounts/XXXXXXXXXXXXXXXXXX/metastores/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> * Host: 
> * Accept: application/json
> * Authorization: REDACTED
> * User-Agent: databricks-tf-provider/1.33.0 databricks-sdk-go/0.28.1 go/1.20.12 os/linux terraform/1.6.5 data/yes resource/metastore auth/azure-client-secret cicd/azure-devops
> * X-Databricks-Azure-Sp-Management-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
< HTTP/2.0 403 Forbidden (Error: unexpected end of JSON input)
< * Date: Fri, 12 Jan 2024 06:48:50 GMT
< * Server: databricks
< * Vary: Accept-Encoding
```

  with data.databricks_metastore.int_meta,
  on metastore_data.tf line 19, in data "databricks_metastore" "int_meta":
  19: data "databricks_metastore" "int_meta" {
=================
Error: unexpected error handling request: unexpected end of JSON input. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:
```
GET /api/2.0/accounts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/scim/v2/Groups?filter=displayName eq 'METASTORE_ADMINS'
> * Host: 
> * Accept: application/json
> * Authorization: REDACTED
> * Content-Type: application/scim+json; charset=utf-8
> * User-Agent: databricks-tf-provider/1.33.0 databricks-sdk-go/0.28.1 go/1.20.12 os/linux terraform/1.6.5 data/yes resource/group auth/azure-client-secret cicd/azure-devops
> * X-Databricks-Azure-Sp-Management-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
< HTTP/2.0 403 Forbidden (Error: unexpected end of JSON input)
< * Date: Fri, 12 Jan 2024 06:48:50 GMT
< * Server: databricks
< * Vary: Accept-Encoding
```

  with data.databricks_group.admins,
  on metastore_data.tf line 24, in data "databricks_group" "admins":
  24: data "databricks_group" "admins" {

**Expected behavior**
it should read the metastore id and then assign it over to required workspace

**Comment by mgyucht** [comment]
This has been fixed in the v0.29.0 version of the Go SDK, which was released in the v1.34.0 version of the TF provider. Upgrade, and this message will go away.
