### ISSUE TITLE
[ISSUE] Error: unexpected error handling request: json: cannot unmarshal number into Go struct field APIErrorBody.error_code of type string.

### ISSUE THREAD

**Issue by madengr00** [databricks/databricks-sdk-go#929]
**Description**

Error: unexpected error handling request: json: cannot unmarshal number into Go struct field APIErrorBody.error_code of type string. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. 
Then the Error message is returned and the github workflow fails.  

**Is it a regression?**
Did this work in a previous version of the SDK? If so, which versions did you try?
I appeared to work in development last week on May22 without returning the error.  On getting the error I tried both the current release, cli/0.220.0 and 0.219.0, still getting error.   Error does not occur in terminal usage, only in Github action. 

**Debug Logs**
```
GET /api/2.0/preview/scim/v2/Me
> * Host: 
> * Accept: application/json
> * Authorization: REDACTED
> * Traceparent: 00-a63c735a684241e3fa6d83ff720ad9b1-e9a9ebb5027dc722-01
> * User-Agent: cli/0.220.0 databricks-sdk-go/0.41.0 go/1.21.10 os/linux cmd/bundle_deploy auth/pat cicd/github
< HTTP/2.0 [40](https://github.com/<ORG>/<REPO>/actions/runs/9274716226/job/25517703872#step:8:41)3 Forbidden
< * Content-Length: 70
< * Content-Type: application/json; charset=utf-8
< * Date: Tue, 28 May 2024 18:44:[43](https://github.com/<ORG>/<REPO>/actions/runs/9274716226/job/25517703872#step:8:44) GMT
< * Server: databricks
< * Vary: Accept-Encoding
< * X-Databricks-Reason-Phrase: Invalid access to Org: 8021675149454685
< {
<   "error_code": 403,
<   "message": "Invalid access to Org: 8021675149[45](https://github.com/<ORG>/<REPO>/actions/runs/9274716226/job/25517703872#step:8:46)4685"
< }
```

**Other Information**
Running in Github Action workflow

**Additional context**

**Comment by MarcusCanto** [comment]
I'm getting a similar issue with a terraform plan:

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: cannot read storage credential: unexpected error handling request: json: cannot unmarshal number into Go struct field APIErrorBody.error_code of type string. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:
│ ```
│ GET /api/2.1/unity-catalog/storage-credentials/mi_storage_credential
│ > * Host: 
│ > * Accept: application/json
│ > * Authorization: REDACTED
│ > * User-Agent: databricks-tf-provider/1.41.0 databricks-sdk-go/0.38.0 go/1.21.9 os/linux terraform/1.7.0 resource/storage_credential auth/pat
│ < HTTP/2.0 403 Forbidden
│ < * Content-Length: 45
│ < * Content-Type: application/json; charset=utf-8
│ < * Date: Wed, 29 May 2024 13:54:33 GMT
│ < * Server: databricks
│ < * Vary: Accept-Encoding
│ < * X-Databricks-Reason-Phrase: user not found
│ < {
│ <   "error_code": 403,
│ <   "message": "user not found"
│ < }
│ ```
│ 
│   with databricks_storage_credential.external_mi,
│   on metastore.tf line 46, in resource "databricks_storage_credential" "external_mi":
│   46: resource "databricks_storage_credential" "external_mi" {
│ 
╵
╷
│ Error: cannot read grants: unexpected error handling request: json: cannot unmarshal number into Go struct field APIErrorBody.error_code of type string. This is likely a bug in the Databricks SDK for Go or the underlying REST API. Please report this issue with the following debugging information to the SDK issue tracker at https://github.com/databricks/databricks-sdk-go/issues. Request log:
│ ```
│ GET /api/2.1/unity-catalog/permissions/metastore/ad5554ac-50e9-4a55-aa36-fd3d87fba036
│ > * Host: 
│ > * Accept: application/json
│ > * Authorization: REDACTED
│ > * User-Agent: databricks-tf-provider/1.41.0 databricks-sdk-go/0.38.0 go/1.21.9 os/linux terraform/1.7.0 resource/grants auth/pat
│ < HTTP/2.0 403 Forbidden
│ < * Content-Length: 45
│ < * Content-Type: application/json; charset=utf-8
│ < * Date: Wed, 29 May 2024 13:54:42 GMT
│ < * Server: databricks
│ < * Vary: Accept-Encoding
│ < * X-Databricks-Reason-Phrase: user not found
│ < {
│ <   "error_code": 403,
│ <   "message": "user not found"
│ < }
│ ```
│ 
│   with databricks_grants.external_mi,
│   on metastore.tf line 57, in resource "databricks_grants" "external_mi":
│   57: resource "databricks_grants" "external_mi" {
│ 
╵

**Comment by pietern** [comment]
@MarcusCanto That sounds like a different issue. Could you open up a new issue for it? Thanks!

@madengr00 I checked and while totally not descriptive, the error could indicate that there are IP access lists for the workspace and that the caller's origin IP is not allowed. Could you check if this is a possible explanation?

**Comment by madengr00** [comment]
When I was trying to pass the databricks bundle deploy command in my Git Action,  I was using 
`[[ "$DATABRICKS_BUNDLE_ENV" == "dev" ]] && databricks bundle deploy --target dev || [[ "$DATABRICKS_BUNDLE_ENV" == "prod" ]] && databricks bundle deploy --target prod`
Perhaps what is happening here is that it was successfully executing the first one, but could not get past the second half since I do not pass both sets of credentials, only the set for the environment being executed on.  
I will close this out and do some additional debugging on my end.
